/**
 * Artix domain model.
 *
 * These types are the contract between every layer: storage (SQLite), search,
 * importers/exporters, the galaxy renderer and the UI. Nothing here imports
 * anything else — the domain has no dependencies, by design.
 *
 * Field names map 1:1 onto SQLite columns (snake_case is converted at the
 * adapter boundary, never here).
 */

/** Milliseconds since the Unix epoch. Artix stores every timestamp this way. */
export type Timestamp = number;

/** Opaque-ish identifiers. Branded so a TagId can never be passed as a SessionId. */
export type SessionId = string & { readonly __brand?: 'SessionId' };
export type MessageId = string & { readonly __brand?: 'MessageId' };
export type ArtifactId = string & { readonly __brand?: 'ArtifactId' };
export type FileRefId = string & { readonly __brand?: 'FileRefId' };
export type TagId = string & { readonly __brand?: 'TagId' };

/* -------------------------------------------------------------- enumerations */

export const SESSION_STATUSES = ['active', 'completed', 'paused', 'archived'] as const;
export type SessionStatus = (typeof SESSION_STATUSES)[number];

/**
 * How a session is drawn in the galaxy. Derived from complexity + status by
 * `classifyCelestial`, but persisted so the layout is stable across restarts
 * and so importers may override it.
 */
export const CELESTIAL_KINDS = ['star', 'planet', 'asteroid'] as const;
export type CelestialKind = (typeof CELESTIAL_KINDS)[number];

export const MESSAGE_ROLES = ['user', 'assistant', 'system', 'tool'] as const;
export type MessageRole = (typeof MESSAGE_ROLES)[number];

/**
 * Non-conversational things a session produced. Kept in one table because they
 * share a shape and because it keeps the "what did I decide?" query to a single
 * indexed scan.
 */
export const ARTIFACT_KINDS = [
  'code', // a code snippet worth keeping
  'architecture', // a described structure / diagram / module map
  'decision', // an explicit choice + rationale
  'todo', // outstanding work
  'command', // a shell command that was run
  'note', // free-form user annotation
] as const;
export type ArtifactKind = (typeof ARTIFACT_KINDS)[number];

/** What happened to a file during the session. Drives the Files tab grouping. */
export const FILE_ACTIONS = ['created', 'modified', 'deleted', 'read', 'referenced'] as const;
export type FileAction = (typeof FILE_ACTIONS)[number];

/* ------------------------------------------------------------------ entities */

/**
 * The central record. One Claude Code session (or any imported equivalent)
 * becomes exactly one Session.
 */
export interface Session {
  readonly id: SessionId;

  title: string;
  /** Logical project name — the clustering key for the galaxy. */
  project: string;
  /** Absolute path on disk this session was working in, when known. */
  folder: string | null;
  /** Short human summary. Generated by importers, editable by the user. */
  summary: string;
  /** Free-form user notes. Never overwritten by re-imports. */
  notes: string;

  /** Primary language, lowercase canonical id from the language registry. */
  language: string | null;
  status: SessionStatus;
  kind: CelestialKind;

  /** 0..1 — drives node radius. Derived from message/file/artifact volume. */
  complexity: number;
  /** 0..1 — drives node brightness. Derived from recency, size and pinning. */
  importance: number;
  /** User-pinned sessions never dim, whatever their age. */
  pinned: boolean;

  /** Identifier of the importer that produced this record (`plugin:importer`). */
  source: string;
  /** Where it came from — a file path, an export id, a folder. */
  sourceRef: string | null;

  /** When the underlying work happened (not when it was imported). */
  startedAt: Timestamp;
  endedAt: Timestamp | null;
  updatedAt: Timestamp;
  importedAt: Timestamp;

  /** Cheap denormalised counters so the galaxy never needs a join to render. */
  messageCount: number;
  fileCount: number;
  artifactCount: number;
  /** Rough token estimate for the whole session; used for context budgeting. */
  tokenEstimate: number;

  /**
   * Stable hash of the imported content. UNIQUE in SQLite — re-importing the
   * same export is a no-op rather than a duplicate star.
   */
  contentHash: string;

  tags: string[];
  technologies: string[];
}

export interface Message {
  readonly id: MessageId;
  readonly sessionId: SessionId;
  /** 0-based position within the session. */
  seq: number;
  role: MessageRole;
  content: string;
  createdAt: Timestamp | null;
  tokenEstimate: number;
  /** Tool name when `role === 'tool'`. */
  toolName: string | null;
}

export interface Artifact {
  readonly id: ArtifactId;
  readonly sessionId: SessionId;
  kind: ArtifactKind;
  title: string;
  /** Language id for `kind === 'code'`, otherwise null. */
  language: string | null;
  content: string;
  /** Associated path, when the artifact belongs to a file. */
  path: string | null;
  /** Index of the message this was extracted from, for "jump to context". */
  messageSeq: number | null;
  /** Only meaningful for `kind === 'todo'`. */
  done: boolean;
}

export interface FileRef {
  readonly id: FileRefId;
  readonly sessionId: SessionId;
  path: string;
  action: FileAction;
  language: string | null;
  /** Byte size when known; -1 when the file was only mentioned. */
  bytes: number;
  /** First ~2 KB of content, for preview without touching the filesystem. */
  snippet: string | null;
}

export interface Tag {
  readonly id: TagId;
  name: string;
  /** CSS colour. Null means "derive from the name hash". */
  color: string | null;
  /** Maintained by storage; used to order the tag filter list. */
  usageCount: number;
}

/**
 * An edge in the knowledge graph. Produced by `deriveLinks` (shared project,
 * shared files, shared technologies) and by future plugins.
 */
export interface SessionLink {
  readonly fromId: SessionId;
  readonly toId: SessionId;
  kind: 'same-project' | 'shared-files' | 'shared-tech' | 'continuation' | 'manual';
  /** 0..1 — drives the opacity of the relationship arc on hover. */
  weight: number;
}

/* ------------------------------------------------- aggregate / view models */

/**
 * Everything needed to render a session workspace. Loaded lazily — the galaxy
 * only ever holds `Session`, never this.
 */
export interface SessionDetail {
  session: Session;
  messages: Message[];
  artifacts: Artifact[];
  files: FileRef[];
  links: SessionLink[];
}

/**
 * The minimal projection the renderer uploads to the GPU. Deliberately flat and
 * numeric: 100k of these must fit comfortably in a few typed arrays.
 */
export interface GalaxyNode {
  id: SessionId;
  title: string;
  project: string;
  language: string | null;
  status: SessionStatus;
  kind: CelestialKind;
  startedAt: Timestamp;
  complexity: number;
  importance: number;
  pinned: boolean;
  technologies: string[];
}

/* ------------------------------------------------------- input / draft types */

/** A session as produced by an importer, before storage assigns identity. */
export interface SessionDraft {
  title: string;
  project: string;
  folder?: string | null;
  summary?: string;
  notes?: string;
  language?: string | null;
  status?: SessionStatus;
  kind?: CelestialKind;
  complexity?: number;
  importance?: number;
  pinned?: boolean;
  source: string;
  sourceRef?: string | null;
  startedAt: Timestamp;
  endedAt?: Timestamp | null;
  tags?: string[];
  technologies?: string[];
  messages?: Omit<Message, 'id' | 'sessionId'>[];
  artifacts?: Omit<Artifact, 'id' | 'sessionId'>[];
  files?: Omit<FileRef, 'id' | 'sessionId'>[];
}

/** Fields the UI is allowed to patch directly. */
export type SessionPatch = Partial<
  Pick<
    Session,
    | 'title'
    | 'project'
    | 'folder'
    | 'summary'
    | 'notes'
    | 'language'
    | 'status'
    | 'kind'
    | 'pinned'
    | 'tags'
    | 'technologies'
  >
>;

/* ------------------------------------------------------------------ queries */

export interface DateRange {
  from: Timestamp | null;
  to: Timestamp | null;
}

/** The full query surface. Every field is optional and ANDed together. */
export interface SearchQuery {
  /** Raw user text, including any `key:value` filter syntax. */
  text: string;
  tags: string[];
  technologies: string[];
  languages: string[];
  projects: string[];
  statuses: SessionStatus[];
  range: DateRange;
  /** When false, archived sessions are excluded. */
  includeArchived: boolean;
  sort: SearchSort;
  limit: number;
  offset: number;
}

export const SEARCH_SORTS = ['relevance', 'recent', 'oldest', 'complexity', 'title'] as const;
export type SearchSort = (typeof SEARCH_SORTS)[number];

export interface SearchHit {
  session: Session;
  /** Higher is better. Combined BM25 + recency + importance, see `rank.ts`. */
  score: number;
  /** `[start, end)` offsets into the field, for highlighting. */
  highlights: Highlight[];
  /** Which matching strategy produced the hit — surfaced in the UI as a chip. */
  via: 'exact' | 'fts' | 'fuzzy' | 'filter';
}

export interface Highlight {
  field: 'title' | 'project' | 'summary' | 'notes' | 'body' | 'tags' | 'technologies';
  start: number;
  end: number;
}

export interface SearchResult {
  hits: SearchHit[];
  /** Total matches ignoring limit/offset. */
  total: number;
  /** Wall-clock milliseconds, shown in the search HUD. */
  elapsedMs: number;
}

/** Aggregate counts used by the filter sidebar and the stats panel. */
export interface Facets {
  languages: FacetBucket[];
  projects: FacetBucket[];
  tags: FacetBucket[];
  technologies: FacetBucket[];
  statuses: FacetBucket[];
}

export interface FacetBucket {
  value: string;
  count: number;
}

export interface LibraryStats {
  sessionCount: number;
  messageCount: number;
  artifactCount: number;
  fileCount: number;
  projectCount: number;
  tokenEstimate: number;
  earliest: Timestamp | null;
  latest: Timestamp | null;
  /** Bytes on disk for the SQLite database. */
  databaseBytes: number;
}

/* ----------------------------------------------------------------- defaults */

export const EMPTY_QUERY: SearchQuery = {
  text: '',
  tags: [],
  technologies: [],
  languages: [],
  projects: [],
  statuses: [],
  range: { from: null, to: null },
  includeArchived: false,
  sort: 'relevance',
  limit: 200,
  offset: 0,
};

export function emptyQuery(overrides: Partial<SearchQuery> = {}): SearchQuery {
  return {
    ...EMPTY_QUERY,
    ...overrides,
    tags: [...(overrides.tags ?? [])],
    technologies: [...(overrides.technologies ?? [])],
    languages: [...(overrides.languages ?? [])],
    projects: [...(overrides.projects ?? [])],
    statuses: [...(overrides.statuses ?? [])],
    range: { ...EMPTY_QUERY.range, ...overrides.range },
  };
}

/** True when the query would match everything (used to skip search entirely). */
export function isBlankQuery(q: SearchQuery): boolean {
  return (
    q.text.trim() === '' &&
    q.tags.length === 0 &&
    q.technologies.length === 0 &&
    q.languages.length === 0 &&
    q.projects.length === 0 &&
    q.statuses.length === 0 &&
    q.range.from === null &&
    q.range.to === null
  );
}
